on:
 push:
  branches:
   - master

# Jobs needs to part..
jobs:
  setup-build-run-start:
    name: basewebpage
    runs-on: ubuntu-latest

    steps:
    #Checkout
      - name: Checkout Repository
        uses: actions/checkout@v3
    #Build Docker:
      - name: docker build
        run: |
          docker build -t baseline.jfrog.io/docker/baseline:1.1.1 .
          docker images
      - name: Login to JFrog Container Registry
        uses: docker/login-action@v1
        with:
          registry: https://baseline.jfrog.io
          username: dhivkrish142@gmail.com
          password: Dhivkk@#21
    #Docker Push:
      - name: docker image Push
        run: docker push baseline.jfrog.io/docker/baseline:1.1.1
  deploy:
    runs-on: ubuntu-latest
    needs: setup-build-run-start
    steps:
    #Checkout
      - name: Checkout Repository
        uses: actions/checkout@v3
     #Install Kubectl
      - name: install kubernates
        uses: azure/setup-kubectl@v2.0
        with: 
          version: 'v1.27.0'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-2      
      - name: Login to JFrog Container Registry
        uses: docker/login-action@v1
        with:
          registry: https://baseline.jfrog.io
          username: dhivkrish142@gmail.com
          password: Dhivkk@#21
      #Docker Image Pull:
      - name: docker image Pull
        run: docker pull baseline.jfrog.io/docker/baseline:1.1.1
      - name: deploy using EKS cluster.
        run: |
          aws eks update-kubeconfig --name baselinewebDevOps --region us-east-2          
          # kubectl create secret docker-registry basesec --docker-server=https://baseline.jfrog.io --docker-username=skkarthik21@gmail.com --docker-password=Dhivkk@#21 --docker-email=dhivkrish142@gmail.com
          kubectl apply -f k8-baselineweb.yml
      - name: Sleep for 300 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '180s'
      - name: test pod's!
        run: |
          kubectl get svc
          kubectl get pods
          kubectl describe pod baselineweb


        
        
  
